version: '3.9'
services:
  postgres:
    image: postgres:11.3
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: user
    container_name: postgresdb
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  web:
    build: .
    ports:
      - '8081:8081'
    environment:
      - REDISCLOUD_URL=redis://redis
      - DATABASE_URL=user=user password=password host=db dbname=db port=5432 sslmode=verify-full
      - PORT=8081
    depends_on:
      - postgres
      - redis
  redis:
    image: redis
    restart: always
    volumes:
      - redisdata:/data

volumes:
  dbdata: null
  redisdata: null
